### PR TITLE
fix(warnings): fix various swiftlint warnings.

### PR DESCRIPTION
**Pull request by bchrisarriola**
Fixing various swiftlint warnings:
* Trailing whitespace violation
* Variable naming related violations
* Nesting violations
* Number of chars in a single line violations

### CODE REVIEW

**Comment by bchrisarriola** [comment]
To avoid the trailing whitespace violation, make sure you have "Automatically trim trailing whitespace" checked under "Preferences" -> "Text Editing"

**Comment by achtenhagen** [comment]
I think Xcode just ignores this setting for me 😒

**Comment by bchrisarriola** [comment]
@achtenhagen you may have to CMD+S on the file?

**Comment by achtenhagen** [comment]
Yeah, I repeatedly press it and in the `git status` output if magically goes away, so I think the editor has its own routine to trim the lines.

**Pull request merged**
