### PR TITLE
fix(KYC): hide back button titles

### PR DESCRIPTION
**Pull request by achtenhagen**
## Objective

Hide the back button title on each screen in the KYC flow.

## Description

This was achieved by adding an empty back button item to `KYCBaseViewController`.

## Merge Checklist

- [x] The PR uses a title supported by [.changelogrc](https://github.com/blockchain/My-Wallet-V3-iOS/blob/dev/.changelogrc#L6...L69).
- [x] Areas of technical debt are marked with a `// TICKET:` comment that includes a ticket number.
- [x] All unit tests pass.
- [ ] You have added unit tests.
- [x] New files added are within the correct directory. (e.g. if a file is required for unit tests to compile, be sure it is added to the tests target.)

### CODE REVIEW

**Comment by thisisalexmcgregor** [comment]
Up to you if you want to update how we handle this with how I described in the other PR. I'm fine with circling back to it later, as long as we `// TICKET` it so we don't forget.

**Comment by achtenhagen** [comment]
@thisisalexmcgregor Will definitely implement your idea, but the ticket option sounds good at least until we have some more bandwidth.

**Comment by achtenhagen** [comment]
@thisisalexmcgregor Add the ticket comment to keep track of the tech debt. Would be great to get this merged soon!

**Comment by thisisalexmcgregor** [comment]
@achtenhagen ✅

**Pull request merged**
