### PR TITLE
iPhone X Support for Request Screen

### PR DESCRIPTION
**Pull request by achtenhagen**
Highlights in this PR:
- Adds iPhone X support to the **Request Screen**.

### IMPORTANT
Please make sure the commit message when merging is:
```
iPhone X Support for Request Screen (#249)
```

### CODE REVIEW

**Comment by woudini** [comment]
QR code images for ETH and BCH should be vertically centered, please change or talk to Brand Lead:
simulator screen shot - iphone 6 - 2018-06-14 at 14 38 33
simulator screen shot - iphone 6 - 2018-06-14 at 14 39 17

**Comment by woudini** [comment]
What was the goal regarding vertical alignment? They are all center-aligned on the iPhone X, but anchored to the top for other phone sizes.

**Comment by achtenhagen** [comment]
The goal was for them to have a consistent offset from the top, but since there is so much extra space on iPhone X, it was decided to increase the top offset for that device.

**Comment by achtenhagen** [comment]
The instructions label now shows on the iPhone 4S as well by making the QR code smaller.

**Comment by woudini** [comment]
Please make the QR code bigger on the 4S. QA was complaining that it was too small for other devices to pick up.

**Pull request merged**
