### PR TITLE
feat(KYC): add Application Complete view controller

### PR DESCRIPTION
**Pull request by achtenhagen**
## Objective

Adds the *Application Completed* screen to the KYC flow.

## Description

Created class + storyboard for this static screen.

## How to Test

Not possible at the moment, unless the VC is instantiated directly from the KYCCoordinator.

## Screenshot

simulator screen shot - iphone x - 2018-08-24 at 14 17 56

## Merge Checklist

- [x] The PR uses a title supported by [.changelogrc](https://github.com/blockchain/My-Wallet-V3-iOS/blob/dev/.changelogrc#L6...L69).
- [ ] Areas of technical debt are marked with a `// TICKET:` comment that includes a ticket number.
- [x] All unit tests pass.
- [ ] You have added unit tests.
- [x] New files added are within the correct directory. (e.g. if a file is required for unit tests to compile, be sure it is added to the tests target.)

### CODE REVIEW

**Comment by bchrisarriola** [comment]
Actually look like the last item is being cut off on iPhone SE: https://cloudup.com/cKglF5H7mZ7

To get around this—should wrap in a `UIScrollView`.

**Comment by thisisalexmcgregor** [comment]
Is there ever a time when one of those things in the list isn't complete? If so, it may need to be either a `UITableViewCell` that we configure with a model that has a title and a completion sate, or a custom view. Also I'm guessing the header values wouldn't say `Done and Done!`. But maybe you can't get to this screen without completing all the steps. 

For localization should the string values be set in the codebase?

**Comment by achtenhagen** [comment]
@thisisalexmcgregor I'm not aware of the possibility to reach this state other than when the flow is completed, hence why I made the UI as static as possible. The header values do indeed say `Done and Done!` as per design. The only way to reach this screen is to complete all of the previous steps.

**Comment by achtenhagen** [comment]
@bchrisarriola Content is already wrapped in a UIScrollView to support smaller devices.

**Pull request merged**
